### ISSUE TITLE
Upgrade mongodb driver to 3.5.7 

### ISSUE THREAD

**Issue by vdobrikov** [vdobrikov/code-talk#2]
In order to fix the following warning its need to upgrade `mongodb` package to `3.5.7` version
```
(node:55) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
coopapp_1    |     at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
coopapp_1    |     at Object.get (internal/modules/cjs/loader.js:664:5)
coopapp_1    |     at Object.<anonymous> (/home/node/app/node_modules/mongodb/lib/operations/db_ops.js:16:42)
coopapp_1    |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
coopapp_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
coopapp_1    |     at Module.load (internal/modules/cjs/loader.js:928:32)
coopapp_1    |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
coopapp_1    |     at Module.require (internal/modules/cjs/loader.js:952:19)
coopapp_1    |     at require (internal/modules/cjs/helpers.js:88:18)
coopapp_1    |     at Object.<anonymous> (/home/node/app/node_modules/mongodb/lib/operations/collection_ops.js:5:23)
...
```

**Comment by vdobrikov** [comment]
https://developer.mongodb.com/community/forums/t/warning-accessing-non-existent-property-count-of-module-exports-inside-circular-dependency/3183

**Comment by vdobrikov** [comment]
Not relevant for Java based backend
